#Nombre del archivo:
name: CI Pipeline

#Sobre donde trabaja:
on:
  pull_request:
  push:
    branches:
      - develop

#Acciones que ejecutará el servidor de GitHub Actions
jobs:
  frontend-build: 
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      #Esto es como hacer un git clone del proyecto a la maquina 
      - name: Checkout repository
        uses: actions/checkout@4

      - name: Setup Node
        uses: actions/setup-node@4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm Install

      - name: Build frontend
        run: npm install